apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: inventory-manager
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/inventorydb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SERVER_PORT: "8083"
